### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ezzatron** [ezzatron/fake-geolocation#1]
- [x] Use classes for `GeolocationPosition` and `GeolocationCoordinates`
- [x] Prevent direct instantiation of classes:
  - [x] `Geolocation`
  - [x] `GeolocationPosition`
  - [x] `GeolocationCoordinates`
  - [x] `GeolocationPositionError`
- [x] Integrate with `fake-permissions`, simulate `PERMISSION_DENIED` errors
  - [x] Time spent waiting for permission does not count towards `timeout`
  - [x] Permission errors take precedence over timeout errors
  - [x] Permissions still in the "prompt" state after requesting permission still result in `PERMISSION_DENIED` errors
  - [x] Ensure that the permission request handler is not called unless the permission state is `PROMPT`
  - [x] Refactor permission requesting to use a "user", similar to `fake-permissions`
  - [x] Make location services accept an optional `Permissions` interface, and track the geolocation permission state from it
- [x] Simulate `TIMEOUT` errors, implement `timeout` option
- [x] Consider using empty `GeolocationPositionError` messages, to prevent reliance on them?
- [x] Split location services into 2 interfaces - one that is read-only, and another that can be mutated
- [x] Make parameter names match MDN / the spec
- [x] Restructure in line with the following spec sections:
  - https://www.w3.org/TR/geolocation/#request-a-position
  - https://www.w3.org/TR/geolocation/#acquire-a-position
- [x] Implement `maximumAge`
- [x] Handle high/low accuracy in location services
- [x] Implement `watchPosition()` and `clearWatch()`
  - [x] Test watching a position with timeout of `0`/negative
    - Android/macOS Chrome: Initial error, followed by successes
    - iOS/macOS Safari: Initial error, no successes
    - Firefox: No errors, only successes
  - [x] Test watching a position with timeout of `1`
    - iOS/macOS Safari: Initial error, followed by successes
    - macOS Chrome: Initial error, followed by non-deterministic successes / errors
  - [x] Test what happens when you change permission state while watching the position
    - [x] Start watching while `denied`/`prompt`, change to `granted`
      - Chrome/Firefox: Immediately errors with `PERMISSION_DENIED`, no positions come through after granting
    - [x] Start watching while `granted`, change to `denied`/`prompt`
      - Chrome: First errors with `POSITION_UNAVAILABLE`, then `PERMISSION_DENIED` in quick succession, no positions come through after re-granting
      - Firefox: No errors, positions just stop coming through, and start back up again after re-granting
- [x] Create geolocation delegate system
- [x] Improve glue code between `fake-geolocation` and `fake-permissions`
- [x] Remove unused error message code
- [x] Consider implementing internal slots with WeakMap instead of symbols
- [x] Consider making edge case behaviors configurable with flags
